/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hurricane.rdf;

import jdk.jshell.JShell;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testShell() {
        JShell shell;
    }

    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
